spring:
  jackson:
    serialization:
      indent_output: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/db_dev"
    username: developer
    password: password
  redis:
    host: localhost
    port: 6379
jwt:
  secret: myjwtsecrettoken
  expiration-duration: 900s #15 minutes
  refresh-expiration-duration: 864000s #10 days